const mongoose = require('mongoose');

/**
 * One real month of booth rent owed - artistId, shopId, amountCents, periodMonth (the calendar
 * month this covers, stored as its UTC first-of-month) and dueDate (that period's real due day,
 * clamped to the month's actual length - see utils/booth-rent.js's dueDateForPeriod).
 *
 * Generated by utils/booth-rent.js's generateDueBoothRentCharges - the booth-rent counterpart to
 * Expense's recurringExpenseId/RecurringExpense relationship, except the terms that produced a
 * given charge (a BoothRentPlan row) are resolved AT GENERATION TIME from whichever plan was in
 * effect for THAT period, never copied from a single live template the way RecurringExpense's
 * amountCents is - a rent change mid-history must not reprice a month whose charge already
 * generated, and it can't, because nothing here points back at BoothRentPlan at all.
 *
 * STATUS LIFECYCLE mirrors Appointment.shopCutStatus's own dual-control shape exactly (see
 * mutations/shopCutPayments.js): 'due' -> 'marked_paid' (the artist's own claim) ->
 * 'confirmed' (the shop's independent confirmation). expenseId/incomeId are set ONLY at
 * 'confirmed' - an invoiced-but-unconfirmed charge isn't real revenue yet, the same ledger-timing
 * rule applyShopCut already follows for the percentage side.
 *
 * The unique index on {artistId, periodMonth} is the idempotency guard for the whole generator,
 * the same role Expense's {recurringExpenseId, date} index plays for RecurringExpense.
 */
const boothRentChargeSchema = new mongoose.Schema({
  artistId: { type: mongoose.Schema.Types.ObjectId, required: true },
  shopId: { type: mongoose.Schema.Types.ObjectId, required: true },
  amountCents: { type: Number, required: true },
  // The UTC first-of-month this charge covers - e.g. 2026-06-01 for June's rent, regardless of
  // which day of June it's actually due.
  periodMonth: { type: Date, required: true },
  dueDate: { type: Date, required: true },
  status: {
    type: String,
    required: true,
    enum: ['due', 'marked_paid', 'confirmed'],
    default: 'due',
  },
  markedPaidAt: { type: Date, default: null },
  markedPaidByUserId: { type: mongoose.Schema.Types.ObjectId, default: null },
  confirmedAt: { type: Date, default: null },
  confirmedByUserId: { type: mongoose.Schema.Types.ObjectId, default: null },
  // Set only once confirmed - see the header comment above.
  expenseId: { type: mongoose.Schema.Types.ObjectId, default: null },
  incomeId: { type: mongoose.Schema.Types.ObjectId, default: null },
  createdAt: { type: Date, required: true, default: Date.now },
});

// The idempotency guard - see the header comment above.
boothRentChargeSchema.index({ artistId: 1, periodMonth: 1 }, { unique: true });
// A shop admin's own roster views (all booth-rent charges at my shop, optionally by status).
boothRentChargeSchema.index({ shopId: 1, status: 1 });
// An artist's own history/current-charge views.
boothRentChargeSchema.index({ artistId: 1, status: 1 });

module.exports = mongoose.model('BoothRentCharge', boothRentChargeSchema);
