const mongoose = require('mongoose');

/**
 * The kinds of flag that can be put on a client.
 *
 * ---------------------------------------------------------------------------------------------
 * A TABLE, NOT AN ENUM, because the user asked to add their own types without a code change. An
 * enum in the schema would mean a deploy every time somebody wants to start tracking "brings their
 * own stencil" or "always late".
 *
 * The cost of that choice, stated plainly: a value that used to be checked by the GraphQL layer is
 * now checked by a lookup, so a typo'd key is a runtime miss rather than a schema error. Flags are
 * created through utils/client-flags.js, which resolves the key against this table and refuses an
 * unknown one - that function is the enforcement, and going around it is how a flag with a key
 * nothing renders gets written.
 *
 * SEEDED TYPES ARE NOT DELETABLE, only deactivated. NO_SHOWED in particular is generated by the
 * system when a session is marked no-show; deleting the type would orphan every flag already
 * pointing at it and make the auto-generation fail silently the next time it ran.
 * ---------------------------------------------------------------------------------------------
 */
const clientFlagTypeSchema = new mongoose.Schema({
  // The stable identifier. Uppercase snake, never shown to a user - `label` is what a person reads,
  // so renaming the label never breaks a stored flag.
  key: { type: String, required: true, uppercase: true, trim: true },
  label: { type: String, required: true, trim: true },
  description: { type: String, default: '' },

  // NULL means a platform-wide type available to every shop. A shopId means a type that shop
  // invented for itself. Both are needed: NO_SHOWED means the same thing everywhere and should not
  // be re-created per shop, and a shop's own vocabulary is nobody else's business.
  shopId: { type: mongoose.Schema.Types.ObjectId, default: null },

  // True for types the SYSTEM raises. A person cannot hand-create one of these, because a flag
  // that claims to be automatic but was typed in by hand is a lie about where the evidence came
  // from - and these are records about a client's conduct.
  systemGenerated: { type: Boolean, default: false },

  // Deactivated rather than deleted. Existing flags of this type stay readable and stop being
  // offered for new ones.
  active: { type: Boolean, default: true },

  createdAt: { type: Date, required: true, default: Date.now },
});

// One type per key per scope. A shop may not shadow a platform type with its own meaning for the
// same key - that would make the same badge mean two things depending on who is looking.
clientFlagTypeSchema.index({ key: 1, shopId: 1 }, { unique: true });

const ClientFlagType = mongoose.model('ClientFlagType', clientFlagTypeSchema);

/**
 * The types that ship with the app.
 *
 * NO_SHOWED is systemGenerated; the other two are manual. NO_TIP is deliberately manual even though
 * a $0 tip on a completed charge could be detected: a client who tips cash, or who was told not to
 * tip, would be flagged by a machine that cannot tell the difference. A record about someone's
 * conduct should have a person behind it.
 */
ClientFlagType.SEEDED = [
  {
    key: 'NO_SHOWED',
    label: 'No-showed',
    description: 'Did not attend a booked session.',
    systemGenerated: true,
  },
  {
    key: 'MOVED_APPOINTMENT',
    label: 'Moved appointment',
    description: 'Rescheduled a booked session.',
    systemGenerated: false,
  },
  {
    key: 'NO_TIP',
    label: 'No tip',
    description: 'Left no tip on a completed session.',
    systemGenerated: false,
  },
];

/** Idempotent - safe to run on every boot and from a seed script. */
ClientFlagType.ensureSeeded = async function ensureSeeded() {
  await Promise.all(
    ClientFlagType.SEEDED.map((type) =>
      ClientFlagType.updateOne(
        { key: type.key, shopId: null },
        // $setOnInsert only: re-running this must never overwrite a label or description somebody
        // has since edited.
        { $setOnInsert: { ...type, shopId: null, active: true, createdAt: new Date() } },
        { upsert: true },
      ),
    ),
  );
};

module.exports = ClientFlagType;
